### ISSUE TITLE
 java.lang.UnsupportedOperationException: empty collection

### ISSUE THREAD

**Issue by kristofa** [openzipkin/zipkin-dependencies-spark#15]
When running the dependencies spark job (published fat jar: zipkin-dependencies-spark-cassandra-1.25.3-all.jar) on our production data we run into following exception:

```
15/12/11 15:29:29 INFO DAGScheduler: Job 0 finished: reduce at ZipkinDependenciesJob.scala:110, took 1079.514477 s
Exception in thread "main" java.lang.UnsupportedOperationException: empty collection
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$apply$36.apply(RDD.scala:1009)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1$$anonfun$apply$36.apply(RDD.scala:1009)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD$$anonfun$reduce$1.apply(RDD.scala:1009)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
	at org.apache.spark.rdd.RDD.reduce(RDD.scala:989)
	at io.zipkin.dependencies.spark.cassandra.ZipkinDependenciesJob$.run(ZipkinDependenciesJob.scala:110)
	at io.zipkin.dependencies.spark.cassandra.ZipkinDependenciesJob$.main(ZipkinDependenciesJob.scala:71)
	at io.zipkin.dependencies.spark.cassandra.ZipkinDependenciesJob.main(ZipkinDependenciesJob.scala)
```

This happens before any data is being written back to Cassandra so we don't have any dependency graph.

**Comment by adriancole** [comment]
taking a look

**Comment by adriancole** [comment]
it isn't obvious to me why the following tries to affect an empty collection. I suppose we can exit early?

```scala
      .reduce(_ + _) // merge DLs under one Dependencies object, which overrides +
```

**Comment by kristofa** [comment]
I took a closer look at the code. Looks like this exception means we have no aggregates at all!

I noticed that our Finagle spans show duplicate annotations in zipkin-web, eg two CS, two CR annotations,... and it looks like `Span.isValid` filters these out. So it might be that this is causing the exception for us. I will investigate in more detail.

**Comment by kristofa** [comment]
I ran the Spark job again and this time it completed but it had only a small subset of our dependencies.

Next I adapted `Span.isValid` to return true in case the service name is defined and removed the check that verifies a span only has 1 instance for each core annotation.  When I ran with this version the full dependency graph appeared in zipkin-web!  It looks like there is an issue with Finagle which makes that the core annotations are submitted multiple times in some cases.

I wonder why @yurishkuro added the single instance annotation check? I don't think it is important for the current dependencies job.

**Comment by yurishkuro** [comment]
@kristofa that check was in the original Hadoop job, I didn't add it. One reason I can think of is if you have ID clash, you may create false positive links between services.

**Comment by kristofa** [comment]
@yurishkuro Right. I didn't think about ID clashes. We should in any case investigate why we have those duplicated annotations. I'll close this issue. Thanks!

**Comment by adriancole** [comment]
clarification: in span stores, the write method is more a patch. ITOW they
shouldn't fail at query time or sink time if an annotation is there twice..
rather it should be ignored. Ignoring is easier said than done in some
implementations. Ex. in mysql we have a conditional on update that won't
overwrite certain fields. Long story short.. the internals of a span store
might have duplicate annotations, but they should return deduped, but in
reality that's hard for many reasons including how to express what a dupe
is.
