### ISSUE TITLE
Switch to gradle

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-dependencies-spark#2]
Our other scala projects uses gradle, and that's also how we publish to bintray, jcenter, and maven central. Let's switch this to gradle so that all of our scala projects build similarly.

**Comment by adriancole** [comment]
cc @jamescway @abesto and me :)

**Comment by abesto** [comment]
Yep, that sounds great. Feel free to ping me if help is needed :)

**Comment by adriancole** [comment]
If you have cycles, help would be gratefully accepted!

**Comment by chemicL** [comment]
Didn't link it, but I migrated the current state of afairs here: https://github.com/openzipkin/zipkin-dependencies-spark/pull/4
I'm planning to work on a fat jar now.

**Comment by yurishkuro** [comment]
Fixed by a59c107afa49885d852aff33834e85eec0fce00e
