### ISSUE TITLE
Support Elasticsearch storage

### ISSUE THREAD

**Issue by vwyuheng** [openzipkin/zipkin-dependencies-spark#21]
What time can depend on the support of elastic analysis

**Comment by adriancole** [comment]
cc @anuraaga

**Comment by adriancole** [comment]
added a note about how to achieve this https://github.com/openzipkin/zipkin-dependencies-spark/issues/22#issuecomment-219330689

**Comment by adriancole** [comment]
here's the initial implementation https://github.com/openzipkin/zipkin-dependencies-spark/pull/33
