### ISSUE TITLE
Failed to open native connection to Cassandra at {127.0.0.1}:9042

### ISSUE THREAD

**Issue by cwoodworth** [openzipkin/zipkin-dependencies-spark#23]
I am running into an issue where both the Fat Jar and gradlew run will not connect to my localhost Cassandra.  I am running Zipkin using Cassandra without issues (data flows successfully).

`env STORAGE_TYPE=cassandra CASSANDRA_CONTACT_POINTS=127.0.0.1 java -jar zipkin.jar`

I am also able to connect to the Cassandra instance using CQLSH without issue.  The Cassandra instance has no user credentials and is running default options.

Could this be a driver issue, and if so how do I verify the versions to ensure they are compliant?

Cassandra 3.5
Zipkin 1.1.4
zipkin-dependencies-spark 1.25.3
Spark 1.5.2

Stack:
`Exception in thread "main" java.io.IOException: Failed to open native connection to Cassandra at {127.0.0.1}:9042
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:164)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:150)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$2.apply(CassandraConnector.scala:150)`

**Comment by adriancole** [comment]
I'm going to guess that this project needs to update the cassandra connector version before it cat access c* 3.5. Right now it is running on v1.4.1 per cassandra/build.gradle

**Comment by cwoodworth** [comment]
Downgrading to C* 2.2.4 solved the issue for now, thanks!

**Comment by Fthi-S3074641** [comment]
Add this next to your --packages dependency, it worked for me perfectly fine.
--conf spark.cassandra.connection.host="127.0.0.1"
